# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='本文章的短网址(Uri identifier).', max_length=255, unique=True, verbose_name='固定链接'),
            preserve_default=False,
        ),
    ]
