# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_auto_20170824_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BLOG.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='文章的类别名', max_length=100, verbose_name='类别名称'),
        ),
    ]
