# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0011_auto_20170825_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='BLOG.Tag'),
        ),
    ]
